//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18033
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionDataHandler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベルを変更")]
        public string Menu_RenameLabelHere {
            get {
                return ((string)(this["Menu_RenameLabelHere"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ここにラベルを設定")]
        public string Menu_SetLabelHere {
            get {
                return ((string)(this["Menu_SetLabelHere"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイルから読み込む")]
        public string Menu_LoadFromFile {
            get {
                return ((string)(this["Menu_LoadFromFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ここにラベル境界を追加")]
        public string Menu_AddLabelBorderHere {
            get {
                return ((string)(this["Menu_AddLabelBorderHere"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Motion_TransparentChecked {
            get {
                return ((bool)(this["Motion_TransparentChecked"]));
            }
            set {
                this["Motion_TransparentChecked"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("第一引数が不正です")]
        public string Msg_InvalidFirstArgument {
            get {
                return ((string)(this["Msg_InvalidFirstArgument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("真理値を指定してください")]
        public string Msg_SpecifyBoolean {
            get {
                return ((string)(this["Msg_SpecifyBoolean"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数値を指定してください")]
        public string Msg_SpecifyNumber {
            get {
                return ((string)(this["Msg_SpecifyNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("値が範囲外です")]
        public string Msg_ValueOutOfRange {
            get {
                return ((string)(this["Msg_ValueOutOfRange"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("シーケンス名を一つ指定してください")]
        public string Msg_SpecifyOneSequenceName {
            get {
                return ((string)(this["Msg_SpecifyOneSequenceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("シーケンスが見つかりません")]
        public string Msg_SequenceNotFound {
            get {
                return ((string)(this["Msg_SequenceNotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("インデックスが範囲外です")]
        public string Msg_IndexOutOfRange {
            get {
                return ((string)(this["Msg_IndexOutOfRange"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("整数値を指定してください")]
        public string Msg_SpecifyInteger {
            get {
                return ((string)(this["Msg_SpecifyInteger"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("カラムのインデックスか，カラム名を指定してください")]
        public string Msg_SpecifyIndexOfColumnOrColumnName {
            get {
                return ((string)(this["Msg_SpecifyIndexOfColumnOrColumnName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("カラム名が見つかりません")]
        public string Msg_ColumnNameNotFound {
            get {
                return ((string)(this["Msg_ColumnNameNotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベル名が見つかりません")]
        public string Msg_LabelNameNotFound {
            get {
                return ((string)(this["Msg_LabelNameNotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}番目の引数が不正です")]
        public string Msg_InvalidNthArgument {
            get {
                return ((string)(this["Msg_InvalidNthArgument"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Motion_DefaultBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["Motion_DefaultBackgroundColor"]));
            }
            set {
                this["Motion_DefaultBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int Script_HistoryCapacity {
            get {
                return ((int)(this["Script_HistoryCapacity"]));
            }
            set {
                this["Script_HistoryCapacity"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイル(&F)")]
        public string Menu_File {
            get {
                return ((string)(this["Menu_File"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("時系列データを開く")]
        public string Menu_OpenTimeSeriesValues {
            get {
                return ((string)(this["Menu_OpenTimeSeriesValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("時系列データを保存")]
        public string Menu_SaveTimeSeriesValues {
            get {
                return ((string)(this["Menu_SaveTimeSeriesValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイルから開く(&O)")]
        public string Menu_OpenFromFile {
            get {
                return ((string)(this["Menu_OpenFromFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベルデータを保存")]
        public string Menu_SaveLabelData {
            get {
                return ((string)(this["Menu_SaveLabelData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベルデータを開く")]
        public string Menu_OpenLabelData {
            get {
                return ((string)(this["Menu_OpenLabelData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ビューパネルを開く")]
        public string Menu_OpenViewPanel {
            get {
                return ((string)(this["Menu_OpenViewPanel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ビューパネルを保存")]
        public string Menu_SaveViewPanel {
            get {
                return ((string)(this["Menu_SaveViewPanel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベル境界の設定(&B)")]
        public string Menu_LabelingBorderSettings {
            get {
                return ((string)(this["Menu_LabelingBorderSettings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ここのラベル境界を削除(&R)")]
        public string Menu_RemoveLabelBorderHere {
            get {
                return ((string)(this["Menu_RemoveLabelBorderHere"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("境界位置の設定(&P)")]
        public string Menu_BorderPositionSettings {
            get {
                return ((string)(this["Menu_BorderPositionSettings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベル名の設定(&N)")]
        public string Menu_LabelNameSettings {
            get {
                return ((string)(this["Menu_LabelNameSettings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("直前の処理の再適用(&A)")]
        public string Menu_ReApplyOperation {
            get {
                return ((string)(this["Menu_ReApplyOperation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("時系列データの処理(&T)")]
        public string Menu_OperationTimeSeriesValues {
            get {
                return ((string)(this["Menu_OperationTimeSeriesValues"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベル列の処理(&L)")]
        public string Menu_OperationLabelSequence {
            get {
                return ((string)(this["Menu_OperationLabelSequence"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("積み重ねグラフモード(&S)")]
        public string Menu_StackGraphMode {
            get {
                return ((string)(this["Menu_StackGraphMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("縮尺をリセット(&R)")]
        public string Menu_ResetScale {
            get {
                return ((string)(this["Menu_ResetScale"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("列を隠す(&H)")]
        public string Menu_HideSequence {
            get {
                return ((string)(this["Menu_HideSequence"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("このビューパネルを閉じる(&C)")]
        public string Menu_CloseThisViewPanel {
            get {
                return ((string)(this["Menu_CloseThisViewPanel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("選択範囲を拡大(&Z)")]
        public string Menu_ZoomSelectedRange {
            get {
                return ((string)(this["Menu_ZoomSelectedRange"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("表示領域を全選択(&V)")]
        public string Menu_SelectVisibleRange {
            get {
                return ((string)(this["Menu_SelectVisibleRange"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("選択範囲を入力(&I)")]
        public string Menu_InputSelectRange {
            get {
                return ((string)(this["Menu_InputSelectRange"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("フレームインデックスを表示(&F)")]
        public string Menu_ShowFrameIndex {
            get {
                return ((string)(this["Menu_ShowFrameIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("再表示")]
        public string Menu_ReView {
            get {
                return ((string)(this["Menu_ReView"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("再適用")]
        public string Menu_ReApply {
            get {
                return ((string)(this["Menu_ReApply"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("選択範囲へ縮小(&U)")]
        public string Menu_UnzoomSelectedRange {
            get {
                return ((string)(this["Menu_UnzoomSelectedRange"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("選択範囲を切り抜き(&C)")]
        public string Menu_ClipSelectedRange {
            get {
                return ((string)(this["Menu_ClipSelectedRange"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("オブジェクト名にnullを指定できません")]
        public string Msg_ObjectNameCannotBeNull {
            get {
                return ((string)(this["Msg_ObjectNameCannotBeNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("オブジェクトが見つかりません")]
        public string Msg_ObjectNotFound {
            get {
                return ((string)(this["Msg_ObjectNotFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("処理の対象とならないオブジェクトが指定されました")]
        public string Msg_InvalidTargetObjectSpecified {
            get {
                return ((string)(this["Msg_InvalidTargetObjectSpecified"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("オブジェクトの選択が不適当です")]
        public string Msg_ImproperObjectSelection {
            get {
                return ((string)(this["Msg_ImproperObjectSelection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("引数の数が不正です")]
        public string Msg_InvalidNumberOfArguments {
            get {
                return ((string)(this["Msg_InvalidNumberOfArguments"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}個の引数が必要です．")]
        public string Msg_NumberOfArgumentsRequired {
            get {
                return ((string)(this["Msg_NumberOfArgumentsRequired"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("引数が不正です")]
        public string Msg_InvalidArgument {
            get {
                return ((string)(this["Msg_InvalidArgument"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("追加されたオブジェクト情報の数と作成されるオブジェクトの数が一致しません")]
        public string Msg_CreateObjectLengthMismatch {
            get {
                return ((string)(this["Msg_CreateObjectLengthMismatch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("オブジェクトを選択してください")]
        public string Msg_PleaseSelectObject {
            get {
                return ((string)(this["Msg_PleaseSelectObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nullを指定できません")]
        public string Msg_CannotSpecifyNull {
            get {
                return ((string)(this["Msg_CannotSpecifyNull"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("点オブジェクトを選択してください")]
        public string Msg_PleaseSelectPointObject {
            get {
                return ((string)(this["Msg_PleaseSelectPointObject"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DialogMotionOperation_IgnoreForm {
            get {
                return ((bool)(this["DialogMotionOperation_IgnoreForm"]));
            }
            set {
                this["DialogMotionOperation_IgnoreForm"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("設定がない場合にダイアログを表示しない")]
        public string Label_DoNotShowDialogIfNoSettings {
            get {
                return ((string)(this["Label_DoNotShowDialogIfNoSettings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ソース")]
        public string Label_Source {
            get {
                return ((string)(this["Label_Source"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("線分オブジェクトを選択してください")]
        public string Msg_PleaseSelectLineObject {
            get {
                return ((string)(this["Msg_PleaseSelectLineObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベル境界を追加(ここまで)")]
        public string Menu_AddLabelBorderUpHere {
            get {
                return ((string)(this["Menu_AddLabelBorderUpHere"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CurrentTimeTabSize {
            get {
                return ((int)(this["CurrentTimeTabSize"]));
            }
            set {
                this["CurrentTimeTabSize"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ラベルを設定 「{0}」")]
        public string Menu_SetLabelWithName {
            get {
                return ((string)(this["Menu_SetLabelWithName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("処理に失敗しました")]
        public string Msg_FailedToOperate {
            get {
                return ((string)(this["Msg_FailedToOperate"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public float Motion_MarginSize {
            get {
                return ((float)(this["Motion_MarginSize"]));
            }
            set {
                this["Motion_MarginSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ファイルが変更されています。保存しますか?")]
        public string Msg_FileModifiedAskSave {
            get {
                return ((string)(this["Msg_FileModifiedAskSave"]));
            }
            set {
                this["Msg_FileModifiedAskSave"] = value;
            }
        }
    }
}
